### ISSUE TITLE
Getting Uncaught TypeError: path.split is not a function in react

### ISSUE THREAD

**Issue by katsuren** [andyyou/react-jetstream-like-demo#1]
In this example, Auth pages are failed to show their page and get error like described in title.

This stackoverflow page helps you to defeat this error.
https://stackoverflow.com/questions/66927051/getting-uncaught-typeerror-path-split-is-not-a-function-in-react

```
react-hook-form updated to 7.0.0 from 6.X.X and has breaking changes:

You have to replace all ref={register} with {...register('value_name')}
```

or install react-hook-form specify version 6.

**Comment by andyyou** [comment]
@katsuren Yes, thanks for the comment. It's needs to be updated.

You can reference branch [react-hook-form-v7](https://github.com/andyyou/react-jetstream-like-demo/tree/react-hook-form-v7)
